### ISSUE TITLE
Artist art for top artist

### ISSUE THREAD

**Issue by Shalasere** [vtr0n/PlayMusicStats#4]
Heya, I've gone ahead and connected it with my music account. Really impressed what you've done here and I'd be happy to help fill out features if you've got any more planned. Currently, it seems that it may not be grabbing any art for top artist. I've taken a screenshot of what I'm seeing. 
![Screenshot_20190908-112155_Chrome](https://user-images.githubusercontent.com/20825532/64491253-d5913200-d22b-11e9-9084-14584302837b.jpg)

**Comment by vtr0n** [comment]
Hey!
I think its problem with viewport tag or trouble with bootstrap grid.

**Comment by vtr0n** [comment]
Solved this problem in pull request #5.
